### ISSUE TITLE
Unexpected platform and fail to load model (Solved onnx with triton not suported on Jetson)

### ISSUE THREAD

**Issue by ncw16** [NVIDIA-AI-IOT/deepstream_triton_model_deploy#10]
Hello,

I am encountering an error when running 
"deepstream-app -c source1_primary_detector.txt"

Regarding the model, I followed the Read.me and ran "run.sh" and have kept the model in the directory indicated in this issue: https://github.com/NVIDIA-AI-IOT/deepstream_triton_model_deploy/issues/5

I haven't made any changes to the centerface.txt file.

Thanks in advance for any help.

Here is the error.

E0208 21:41:07.509156 20068 model_repository_manager.cc:1519] unexpected platform type onnxruntime_onnx for centerface
ERROR: TRTIS: failed to load model centerface, trtis_err_str:INTERNAL, err_msg:failed to load 'centerface', no version is available
ERROR: failed to load model: centerface, nvinfer error:NVDSINFER_TRTIS_ERROR
ERROR: failed to initialize backend while ensuring model:centerface ready, nvinfer error:NVDSINFER_TRTIS_ERROR
0:00:04.427607013 20068     0x35fdeac0 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary_gie> nvinferserver[UID 1]: Error in createNNBackend() <infer_trtis_context.cpp:223> [UID = 1]: failed to initialize trtis backend for model:centerface, nvinfer error:NVDSINFER_TRTIS_ERROR
I0208 21:41:07.509727 20068 server.cc:179] Waiting for in-flight inferences to complete.
I0208 21:41:07.509778 20068 server.cc:194] Timeout 30: Found 0 live models and 0 in-flight requests
0:00:04.427822468 20068     0x35fdeac0 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary_gie> nvinferserver[UID 1]: Error in initialize() <infer_base_context.cpp:78> [UID = 1]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRTIS_ERROR

**Comment by mjhuria** [comment]
Hi,

Could you please print the dir. tree?

**Comment by ncw16** [comment]
Hi @mjhuria 

Here is the dir. tree

.
├── centerface
│   ├── 1
│   │   ├── change_dim.py
│   │   ├── model.onnx
│   │   └── run.sh
│   ├── centerface_labels.txt
│   └── config.pbtxt
├── centerface_output.png
├── config
│   ├── centerface.txt
│   ├── out.mp4
│   └── source1_primary_detector.txt
├── customparser
│   ├── customparserbbox_centernet.cpp
│   ├── libnvds_infercustomparser_centernet.so
│   └── Makefile
└── README.md

**Comment by monjha** [comment]
What system are you using?

**Comment by ncw16** [comment]
I'm using Jetson Xavier NX developer Kit

**Comment by monjha** [comment]
onnx with triton inference server on jetson is not supported.

**Comment by ncw16** [comment]
I see, thanks for the help @monjha
