### ISSUE TITLE
is there any example with python?

### ISSUE THREAD

**Issue by ThiagoMateo** [NVIDIA-AI-IOT/deepstream_triton_model_deploy#12]

**Comment by ghost** [comment]
There are a few examples using a DeepStream with Python here: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/
For Triton with DeepStream refer to the ssd-parser example at: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-ssd-parser
