### ISSUE TITLE
Problem with running centerface model.

### ISSUE THREAD

**Issue by rahulsharma11** [NVIDIA-AI-IOT/deepstream_triton_model_deploy#4]
Hi,
I have installed tritonserver(docker image) and provided centerface model in "model_repository". Docker image successfully loaded the centerface model.

By running -
"deepstream-app -c source1_primary_detector.txt"

I am getting error-
** ERROR: <create_primary_gie_bin:120>: Failed to create 'primary_gie'
** ERROR: <create_primary_gie_bin:182>: create_primary_gie_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:636>: Failed to create pipeline
Quitting
App run failed

Please suggest if few other steps are left or not.
Thanks

**Comment by monjha** [comment]
Hi,
Could you please run GST_DEBUG=3 and then run the application to get more information on the error?

**Comment by rahulsharma11** [comment]
Hi,
Thanks for the reply.

With GST_DEBUG=3 , Following is the output-

0:00:00.039526510 22684 0x559877943610 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "nvinferserver"!
** ERROR: <create_primary_gie_bin:120>: Failed to create 'primary_gie'
** ERROR: <create_primary_gie_bin:182>: create_primary_gie_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:636>: Failed to create pipeline
Quitting
App run failed


I can see in config-file, there is "nvinferserver" plugin-type in primary-gie.
[primary-gie]
enable=1
#(0): nvinfer; (1): nvdsinfer_server
plugin-type=1

**Comment by monjha** [comment]
Hi Rahul,

I still don't see a complete log. Could you please run:
GST_DEBUG=3 and then run
deepstream -c source1_primary_detector.txt
Thanks!

**Comment by rahulsharma11** [comment]
Hi, I ran with the same.
Error is highlighted for your reference-

**0:00:00.039526510 22684 0x559877943610 WARN GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "nvinferserver"!**

If you need i can run GST_DEBUG=4 and provide you logs...That is huge.

**Comment by monjha** [comment]
Thanks Rahul!
Are you able to run any other deepstream test?

**Comment by rahulsharma11** [comment]
Yes.
But without docker environment

**Comment by mjhuria** [comment]
Hi Rahul,

What do you get when you run:
gst-inspect-1.0 nvinferserver

If this has an error then you probably don't have /lib/gst-plugins/libnvdsgst_inferserver.so lib. What DS version are you using?

**Comment by rahulsharma11** [comment]
Hi,
I got "No such element or plugin 'nvinferserver' ".

I am using DS5 with x86.

**Comment by mjhuria** [comment]
You don't need to use the triton inference server docker image to run this application.
Please use deepstream docker image from https://ngc.nvidia.com/catalog/containers/nvidia:deepstream
tag: 5.0.1-20.09-triton

**Comment by rahulsharma11** [comment]
ok thanks
