### ISSUE TITLE
Does nvcr.io/nvidia/deepstream:5.0.1-20.09-triton support TensorRT 7.2.2?

### ISSUE THREAD

**Issue by vilmara** [NVIDIA-AI-IOT/deepstream_triton_model_deploy#7]
Does the docker image nvcr.io/nvidia/deepstream:5.0.1-20.09-triton support models optimized with TensorRT 7.2.2?

**Comment by monjha** [comment]
Hi,

DS5.1 currently supports trt 7.1.3 only.
