### ISSUE TITLE
Not able to run with deepstream sdk.

### ISSUE THREAD

**Issue by rahulsharma11** [NVIDIA-AI-IOT/deepstream_triton_model_deploy#8]
Hi,
Firstly thanks for the project. This is awesome.

I have few doubts-
1) When i run this with dockerised tritonserver based deepstream image and follow the steps, it runs awesome. 
But how can i made it run with batch-size > 1.

2) I tried to run with deepstream sdk and updated the config file also. There was no face detection.
I tried to debug the heatmap dims output in custom_parser.cpp, 
Debug results-
heatmap->inferDims[0] =  1
heatmap->inferDims[1] =  8
heatmap->inferDims[2] =  8
heatmap->inferDims[3] = 0
face detected = 0

While debugging with docker tritonserver based deepstream i got (Where i get detections)-
heatmap->inferDims[0] =  1
heatmap->inferDims[1] =  1
heatmap->inferDims[2] =  120
heatmap->inferDims[3] =  160
face size 3

What is the issue with model dims? how can i use this with deepstream sdk? is there parsing logic need to be changed?
I also provided infer-dims = 0(NCHW). in infer-config configuration. But no results.

Note-
I also tried to load the model as tensorRT code, it gave me error for model-
error is-
[TRT]   binding to input 0 input.1  binding index:  0
[TRT]   binding to input 0 input.1  dims (b=1 c=1 h=3 w=480) size=5760
[TRT]   binding to output 0 537  binding index:  1
[TRT]   binding to output 0 537  dims (b=1 c=1 h=1 w=120) size=480
[TRT]   binding to output 1 538  binding index:  2
[TRT]   binding to output 1 538  dims (b=1 c=1 h=2 w=120) size=960
[TRT]   binding to output 2 539  binding index:  3
[TRT]   binding to output 2 539  dims (b=1 c=1 h=2 w=120) size=960
[TRT]   binding to output 3 540  binding index:  4
[TRT]   binding to output 3 540  dims (b=1 c=1 h=10 w=120) size=4800

Please suggest how can i use this model with deepstream sdk.
Will appreciate.
Thanks.

**Comment by monjha** [comment]
Hi Rahul,

For question 1, you can update the batch size in the configuration file (config.pbtxt and centerface.txt). 
For your second question, what model are you trying to deploy?

**Comment by rahulsharma11** [comment]
Hi,
Thanks for the reply.
**For question 1, you can update the batch size in the configuration file (config.pbtxt and centerface.txt).**
I am getting following error while making "max-batch-size=2" in config.pbtxt and centerface.txt-

Initializing Triton Inference Server
E0210 04:54:59.121138 719 model_repository_manager.cc:1519] unable to autofill for 'centerface', configuration specified max-batch 2 but model session does not support batching
ERROR: infer_trtis_server.cpp:617 TRTIS: failed to load model centerface, trtis_err_str:INTERNAL, err_msg:failed to load 'centerface', no version is available
ERROR: infer_trtis_backend.cpp:42 failed to load model: centerface, nvinfer error:NVDSINFER_TRTIS_ERROR
ERROR: infer_trtis_backend.cpp:184 failed to initialize backend while ensuring model:centerface ready, nvinfer error:NVDSINFER_TRTIS_ERROR
0:00:02.252326544   719 0x55e0b9e3c040 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary_gie> nvinferserver[UID 1]: Error in createNNBackend() <infer_trtis_context.cpp:223> [UID = 1]: failed to initialize trtis backend for model:centerface, nvinfer error:NVDSINFER_TRTIS_ERROR
I0210 04:54:59.121824 719 server.cc:179] Waiting for in-flight inferences to complete.
I0210 04:54:59.121837 719 server.cc:194] Timeout 30: Found 0 live models and 0 in-flight requests
0:00:02.252422373   719 0x55e0b9e3c040 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary_gie> nvinferserver[UID 1]: Error in initialize() <infer_base_context.cpp:78> [UID = 1]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRTIS_ERROR

2) **For your second question, what model are you trying to deploy?**
I tested with 2 models-
first model is which is obtained by running the "run.sh" script. Then i convert that model.onnx to model.engine with command - "trtexec --explicitBatch --onnx=model.onnx".
Then the errorr is -
heatmap->inferDims[0] = 1
heatmap->inferDims[1] = 8
heatmap->inferDims[2] = 8
heatmap->inferDims[3] = 0
face detected = 0


I tested another model from "https://github.com/Star-Clouds/CenterFace/tree/master/models/onnx".
There i get error-
heatmap->inferDims[0] = 1
heatmap->inferDims[1] = 120
heatmap->inferDims[2] = 160
heatmap->inferDims[3] = 0
face size 0

Not sure but i think this is dims issue with regarding model.
It will nice if you can guide me the correct centerface model suitable for deepstream sdk.
Thanks

**Comment by rahulsharma11** [comment]
Hi,
Any update on this?

**Comment by rahulsharma11** [comment]
> Hi Rahul,
> 
> For question 1, you can update the batch size in the configuration file (config.pbtxt and centerface.txt).
> For your second question, what model are you trying to deploy?

Hi,
Let me know if any research is going on this or you are not able to reproduce the issue. I need to run this on deepstream sdk.

**Comment by monjha** [comment]
Hi,

For this error: 
_"unable to autofill for 'centerface', configuration specified max-batch 2 but model session does not support batching"_

What batch size you have in the model? You will need to either add a dynamic batch size (-1) or update the model with batch size you want to use in inference. If you are using the run.sh, we used batch size 1. You will need to update that.

**Comment by rahulsharma11** [comment]
Hi,
Are you able to run this on deepstream sdk? as you mentioned that it can be run on deepstream sdk or deepstream-triton-server image.

Please test deepstream sdk, and let me know for the steps to run as it does not run straight away.
Thanks.

**Comment by rahulsharma11** [comment]
Hi,
Can i save engine file while running triton server based deepstream image?

I think if i can use the generated model from docker deepstream to deepstream sdk to get the output

**Comment by monjha** [comment]
> Hi,
> Are you able to run this on deepstream sdk? as you mentioned that it can be run on deepstream sdk or deepstream-triton-server image.
> 
> Please test deepstream sdk, and let me know for the steps to run as it does not run straight away.
> Thanks.

Hi Rahul,

For batch size: you need to update the input dimension for onnx model and then update the configuration file. Are you getting any issues with this method?

**Comment by monjha** [comment]
> Hi,
> Can i save engine file while running triton server based deepstream image?
> 
> I think if i can use the generated model from docker deepstream to deepstream sdk to get the output

You can create an engine file offline. trtis+ DS doesn't save engine files. Please check this link https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/trtexec/README.md

**Comment by rahulsharma11** [comment]
> > Hi,
> > Are you able to run this on deepstream sdk? as you mentioned that it can be run on deepstream sdk or deepstream-triton-server image.
> > Please test deepstream sdk, and let me know for the steps to run as it does not run straight away.
> > Thanks.
> 
> Hi Rahul,
> 
> For batch size: you need to update the input dimension for onnx model and then update the configuration file. Are you getting any issues with this method?

Hi thanks for the reply.
Currently i am not bothering about batch-size as i am having issue if i run the project(centerface) with deepstream sdk locally.
Its a bit urgent for me so i will appreciate your help on this.

I will reference my observation again-
1) with deepstream tritonserver based image, it runs good with batch-size =1
2) With deepstream sdk , it does not run. 
I want to run this with deepstream sdk only.

**Comment by rahulsharma11** [comment]
> check

Thanks for the point.

I know this trtexec utility. I asked this because i have tried all the conversions and tried to run with deepstream sdk but no suceess.
Please let me know if you are able to test the centerface project with deepstream sdk. If yes then let me know the steps to reproduce the config-primary file and model file.

**Comment by monjha** [comment]
Okay, how did you install Deepstream SDK so I can try to reproduce the issue?

**Comment by rahulsharma11** [comment]
I downloaded the tar file of deepstream-sdk-5.0.
https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_Quickstart.html#dgpu-setup-for-ubuntu
command for reference- "sudo tar -xvf deepstream_sdk_v5.0.0_x86_64.tbz2 -C /"

I tested the deepstream-app.

Steps to reproduce the issue-
1) download the centerface "git clone https://github.com/NVIDIA-AI-IOT/deepstream_triton_model_deploy"
2) cd deepstream_triton_model_deploy/centerface/config
3) change the plugin-type=0 (for nvinfer) in primary-gie group.
3) deepstream-app -c source1_primary_detector.txt

result-
It will straightaway give error as "centerface.txt" is according to "nvinferserver" plugin-type in primary-gie.

troubleshooting-
i updated the config-infer.txt and source1_primary_detector.txt according to deepstream-sdk. PFA for reference.
[text-file.zip](https://github.com/NVIDIA-AI-IOT/deepstream_triton_model_deploy/files/6033451/text-file.zip)

then run -
deepstream-app -c source1_primary_detector_sdk.txt

result-
There is no detected output.

**Comment by monjha** [comment]
checked your config file. Seems like the issue might be with input and output dimensions. Can you update the input and output dimensions of onnx model? Default dim I guess are 32x32 and that's why you are getting 8x8 in the output blob.You can refer change_dim.py function.

    inputs[0].type.tensor_type.shape.dim[0].dim_value = 1
    inputs[0].type.tensor_type.shape.dim[2].dim_value = 480
    inputs[0].type.tensor_type.shape.dim[3].dim_value = 640

    for output in outputs:
        output.type.tensor_type.shape.dim[0].dim_value = 1
        output.type.tensor_type.shape.dim[2].dim_value = 120 #
        output.type.tensor_type.shape.dim[3].dim_value = 160

**Comment by rahulsharma11** [comment]
Yes i changed the model dims according to your suggestions. Verified in Netron also.
Still no luck. But i suspect its a dims mismatch issue only.

[HINT]-
I checked the "heatmap->inferDims"(in customparsing code) values also , these are-
heatmap->inferDims[-1] = 3
heatmap->inferDims[0] = 1
heatmap->inferDims[1] = 120
heatmap->inferDims[2] = 160
heatmap->inferDims[3] = 0

This shows the issue with dims shifted.

As tritonserver based deepstream is giving me-
heatmap->inferDims[-1] = 4
heatmap->inferDims[0] = 1
heatmap->inferDims[1] = 1
heatmap->inferDims[2] = 120
heatmap->inferDims[3] = 160

There is something updated from 3 dims to 4 dims. I don't know how/why.

**Comment by monjha** [comment]
Hi,

I was able to change the dimensions and getting the same result as trtis. How come you are getting heatmap->inferDims[3] = 0 if you have updated the Dims[3]?

**Comment by rahulsharma11** [comment]
Not sure why.
This is my updated onnx model-

[model_480x640.zip](https://github.com/NVIDIA-AI-IOT/deepstream_triton_model_deploy/files/6041088/model_480x640.zip)

Can you just check if it is updated correctly?
Also did you update any changes in config file?

**Comment by rahulsharma11** [comment]
Hi, can this be the version mismatch issue? 
i am using DS5.0.0 , Trt7.2.1 with cuda10.2.

what version did you use?

**Comment by rahulsharma11** [comment]
Hi,
With the reference of this "https://github.com/CaoWGG/TensorRT-CenterNet/blob/f949252e37b51e60f873808f46d3683f15735e79/src/utils.cpp",
I can see, there is Input_format conversion (from  HWC TO CHW).

This may be the main cause for the model not working with deepstream sdk localy with nvinfer.
Did this model supports HWC?

**Comment by rahulsharma11** [comment]
Closing the issue. I got it working. 
There was issue with getting heatmap_dims[2], and [3]. So i hardcoded it.

**Comment by Darshcg** [comment]
Hi @rahulsharma11,

I am facing exactly the same issue. Can you please help me how you reolved it?

> There was issue with getting heatmap_dims[2], and [3]. So i hardcoded it.

Can you please elobarate this?
Would be a great help from yourside.

I have posted the issue in Nvidia Forum:
https://forums.developer.nvidia.com/t/no-detection-for-centerface-model-inference-with-deepstream-for-centerface/174332


Thanks,
Darshan

**Comment by rahulsharma11** [comment]
Hi,
In the parsing code, you can provide fea_w, fea_h values manually. Like -
"120" instead of heatmap->inferDims[2] and "160" instead of heatmap->inferDims[3].

**Comment by Darshcg** [comment]
Hi @rahulsharma11,

I am desperately looking forwards to your reply.

Thanks

**Comment by Darshcg** [comment]
Hi @rahulsharma11,

Thank you very much for your kind reply.
I have changed the same, and now I am getting the Detection. But the Detections are not coming properly. 
I attaching the sample output below
![Screenshot from 2021-04-06 23-22-12](https://user-images.githubusercontent.com/48723743/113759482-bf629500-9732-11eb-9c01-78d8c05f6fe7.png)

May I know why I am facing this issue?

Thanks,
Darshan

**Comment by rahulsharma11** [comment]
Check the model input and output size.

**Comment by Darshcg** [comment]
Hi @rahulsharma11,

Thanks for your reply.
The input and output sizes are:
input: [1,3,480, 640]
output: [1,1,120,160](537), [1,2,120,160](538), [1,2,120,160](539), [1,10,120,160](540)

I hope these are correct. Do I need to hardcode these values in the config files or in custom parser code?

Thanks

**Comment by Darshcg** [comment]
Hi @rahulsharma11,

Can you please provide your config files(from which you got the correct detection with only Deepstream)?
Would be a great help from yourside.

Thanks

**Comment by rahulsharma11** [comment]
Hi sorry for late reply,
Did you solve the isuue?
